export const actionTypes = {
    SET_MOVIE_LIST: "SET_MOVIE_LIST",
    SET_DETAIL_MOVIE: "SET_DETAIL_MOVIE",
    USER_SIGN_UP: "USER_SIGN_UP",
    USER_SIGN_IN: "USER_SIGN_IN",
    FETCH_ME: "FETCH_ME",
    USER_LOGOUT: "USER_LOGOUT",
    SET_BANNER_LIST: "SET_BANNER_LIST",
    SET_SYSTEM_THEATER: "SET_SYSTEM_THEATER"
}